from typing import List, Optional
from pydantic import BaseModel
from typing import Dict


# Original scan result
class VulnScan(BaseModel):
    id: str  # GHSA ID
    related_id: str  # CVE ID
    related_vuln_datasource: str
    language: str
    package_name: str
    package_version: str
    fixed_version: Optional[str] = None
    cvss_v2_score: Optional[float] = None
    cvss_v2_version: Optional[str] = None
    cvss_v3_score: Optional[str] = None  # CVSS vector string
    cvss_v3_version: Optional[str] = None
    cvss_v4_vector: Optional[str] = None
    cvss_v4_version: Optional[str] = None
    epss_score: Optional[float] = None
    epss_percentile: Optional[float] = None
    summary: str
    description: str
    references: List[str]

    # Code context fields for remediation generation
    file_path: Optional[str] = None  # Path to vulnerable file
    line_number: Optional[int] = None  # Line number of vulnerability
    code_snippet: Optional[str] = None  # Surrounding code context
    function_name: Optional[str] = None  # Function containing vulnerability
    repo_url: Optional[str] = None  # Repository URL
    commit_hash: Optional[str] = None  # Commit being analyzed
    branch: Optional[str] = None  # Branch being analyzed


# Enriched result returned by assessment
class VulnAssessment(VulnScan):
    kev: bool | None = None
    risk_score: float | None = None
    risk_label: str | None = None
    rationale: Optional[str] = None


# Remediation items returned by the remediate step
class Remediation(BaseModel):
    cve_id: str
    package_name: str
    current_version: str
    recommendation: str
    references: List[str] = []

    # if we're making a PR with fix, these fields will be populated
    fix_type: Optional[str] = (
        None  # "dependency_upgrade", "code_change", "config_change"
    )
    generated_fix: Optional[str] = None  # The actual code fix generated by Llama
    file_path: Optional[str] = None  # File to be modified
    line_number: Optional[int] = None  # Line number to be modified
    pr_title: Optional[str] = None  # Suggested PR title
    pr_description: Optional[str] = None  # Detailed PR description
    confidence_score: Optional[float] = None  # Llama's confidence in the fix (0.0-1.0)
    alternative_fixes: Optional[List[str]] = None  # Alternative fix suggestions


class AssessRequest(BaseModel):
    findings: List[VulnScan]


class AssessResponse(BaseModel):
    repo_url: Optional[str] = None
    findings: List[VulnAssessment]
    artifacts: Optional[Dict[str, str]] = None
